# Title
[]()

In [3]:

import sys
sys.path.append(r"/home/silvhua/custom_python")
sys.path.append(r"/home/silvhua/repositories/notion/src")
from silvhua import *
from wrangling import *
# from notion_functions import *

In [40]:
# set the option to wrap text within cells
pd.set_option('display.max_colwidth', 100)
# pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Load Data

In [49]:
path = '../data'
filename = 'notion_df_test.sav'
df = loadpickle(filename, path)
df

	Time completed: 2024-01-11 00:38:51.837831
Dataframe shape:  (268, 16)
DataFrame columns: ['Name', 'created_time', 'Task Tag', 'Flag', 'Elapsed', 'Task Name', 'Task Project tags', 'Task Parent-task', 'Task Sub-tasks', 'Task Project name', 'start time', 'end time', 'Roadmap Item', 'url', 'id', 'Notes']

,Name,created_time,Task Tag,Flag,Elapsed,Task Name,Task Project tags,Task Parent-task,Task Sub-tasks,Task Project name,start time,end time,Roadmap Item,url,id,Notes
0,2023-12-01 07:58,2023-12-01 07:58:00-08:00,[life],None,0.283333,Solarathon team communication,[[portfolio]],[None],[None],Solarathon,07:02,07:19,[],https://www.notion.so/2023-12-01-07-58-465451701dbd49ad85f14da2db08b4a1,46545170-1dbd-49ad-85f1-4da2db08b4a1,NaN
1,2023-12-01 08:36,2023-12-01 08:36:00-08:00,[life],None,0.333333,Solarathon meeting,[[portfolio]],[None],[None],Solarathon,08:10,08:30,[],https://www.notion.so/2023-12-01-08-36-936a18406c0b44ef8252c0676475e70e,936a1840-6c0b-44ef-8252-c0676475e70e,NaN
2,2023-12-01 08:37,2023-12-01 08:37:00-08:00,[life],None,1.333333,Solarathon meeting,[[portfolio]],[None],[None],Solarathon,08:30,09:50,[],https://www.notion.so/2023-12-01-08-37-faf64d4c365e4d5dbb0774179507f2eb,faf64d4c-365e-4d5d-bb07-74179507f2eb,NaN
3,2023-12-01 09:59,2023-12-01 09:59:00-08:00,[life],None,0.15,Solarathon general communication,[[portfolio]],[None],[None],Solarathon,09:50,09:59,[],https://www.notion.so/2023-12-01-09-59-281af44a4d9a440e9e728db75906264c,281af44a-4d9a-440e-9e72-8db75906264c,NaN
4,2023-12-01 11:02,2023-12-01 11:02:00-08:00,[Ginkgo],None,0.283333,Ginkgo daily stand up meeting,[[Ginkgo work]],[None],[None],Ginkgo meetings,11:00,11:17,[],https://www.notion.so/2023-12-01-11-02-793df29322da4b3f85f12436f7f3032f,793df293-22da-4b3f-85f1-2436f7f3032f,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,2023-12-29 20:40,2023-12-29 20:40:00-08:00,[life],None,0.15,personal sprint planning,[[admin]],[None],[None],Admin,20:40,20:49,[],https://www.notion.so/2023-12-29-20-40-eaa738e0b8aa407db559d353c1688fe8,eaa738e0-b8aa-407d-b559-d353c1688fe8,NaN
266,2023-12-29 20:50,2023-12-29 20:50:00-08:00,[Ginkgo],"[{'id': 'pBGI', 'name': 'flag', 'color': 'red'}]",1.016667,Checking Exercises Post Publishing,[[Ginkgo work]],[None],[None],Ginkgo app testing,20:50,21:51,[],https://www.notion.so/2023-12-29-20-50-a3984ccbbf9b431496153ae393717ac9,a3984ccb-bf9b-4314-9615-3ae393717ac9,NaN
267,2023-12-30 09:41,2023-12-30 09:41:00-08:00,[life],None,0.816667,learn Solara,"[[life, tech ed, admin]]",[None],[None],Notion analytics,9:41,9:50,[],https://www.notion.so/2023-12-30-09-41-c3e719b6f92c4c2aa6ffec0f28c2e42c,c3e719b6-f92c-4c2a-a6ff-ec0f28c2e42c,NaN
268,2023-12-30 11:14,2023-12-30 11:14:00-08:00,[life],None,0.166667,MASS audio roundtable,"[[Defy Time Fitness, life]]",[None],[None],kinesiology continuing education,11:10,11:20,[],https://www.notion.so/2023-12-30-11-14-53245a2135e546da995eb547cc0bf860,53245a21-35e5-46da-995e-b547cc0bf860,NaN
269,2024-01-10 12:00,2024-01-10 12:00:00-08:00,[Defy Time Fitness],None,0.316667,Coach McLoone client programs,[Defy Time Fitness],[None],[None],Coach McLoone,12:04,12:23,[],https://www.notion.so/2024-01-10-12-00-c6bd706682f44e85ba235db2eea7c6ea,0,2024-01-10 12:00 https://app.asana.com/0/1195521695979971/1206304573045450/f \n—

In [4]:
filters = {
    'Notes': 'notnull'
}
filter_df_all_conditions(df, filters, verbose=False)

Date column dtype: object
Results where ALL conditions are met:
	DataFrame indices: [113, 269]
	DataFrame shape: (2, 16)

,Name,created_time,Task Tag,Flag,Elapsed,Task Name,Task Project tags,Task Parent-task,Task Sub-tasks,Task Project name,start time,end time,Roadmap Item,url,id,Notes
113,2023-12-12 00:46,2023-12-12 04:01:00-08:00,[life],None,4.55,personal dev ops,[admin],[None],[None],Admin,00:46,05:19,[],https://www.notion.so/2023-12-12-00-46-47e6bba...,2,2023-12-12 00:46 reset Windows after accident...
269,2024-01-10 12:00,2024-01-10 12:00:00-08:00,[Defy Time Fitness],None,0.316667,Coach McLoone client programs,[Defy Time Fitness],[None],[None],Coach McLoone,12:04,12:23,[],https://www.notion.so/2024-01-10-12-00-c6bd706...,0,2024-01-10 12:00 https://app.asana.com/0/1195...

In [17]:
df[df['Roadmap Item'] == True]

Empty DataFrame
Columns: [Name, created_time, Task Tag, Flag, Elapsed, Task Name, Task Project tags, Task Parent-task, Task Sub-tasks, Task Project name, start time, end time, Roadmap Item, url, id, Notes]
Index: []

# show relevant columns for invoices

In [6]:
[col for col in df.columns]

['Name',
 'created_time',
 'Task Tag',
 'Flag',
 'Elapsed',
 'Task Name',
 'Task Project tags',
 'Task Parent-task',
 'Task Sub-tasks',
 'Task Project name',
 'start time',
 'end time',
 'Roadmap Item',
 'url',
 'id',
 'Notes']

In [21]:
 df['created_time'].dtypes

datetime64[ns, America/Vancouver]

In [41]:
def invoice_timesheet(df, include_roadmap_item=True):
    df['Date'] = df['Name'].str.extract(r'(\d{4}-\d{2}-\d{2})', expand=False)
    invoice_columns = [
        'Date',
        'Task Project name',
        'start time',
        'end time',
        'Elapsed',
        'Task Name',
        'Notes'
    ]
    if include_roadmap_item:
        invoice_columns.insert(2, 'Roadmap Item')
    return df[invoice_columns]

invoice_timesheet(df)

,Date,Task Project name,Roadmap Item,start time,end time,Elapsed,Task Name,Notes
0,2023-12-01,Solarathon,[],07:02,07:19,0.283333,Solarathon team communication,NaN
1,2023-12-01,Solarathon,[],08:10,08:30,0.333333,Solarathon meeting,NaN
2,2023-12-01,Solarathon,[],08:30,09:50,1.333333,Solarathon meeting,NaN
3,2023-12-01,Solarathon,[],09:50,09:59,0.15,Solarathon general communication,NaN
4,2023-12-01,Ginkgo meetings,[],11:00,11:17,0.283333,Ginkgo daily stand up meeting,NaN
...,...,...,...,...,...,...,...,...
265,2023-12-29,Admin,[],20:40,20:49,0.15,personal sprint planning,NaN
266,2023-12-29,Ginkgo app testing,[],20:50,21:51,1.016667,Checking Exercises Post Publishing,NaN
267,2023-12-30,Notion analytics,[],9:41,9:50,0.816667,learn Solara,NaN
268,2023-12-30,kinesiology continuing education,[],11:10,11:20,0.166667,MASS audio roundtable,NaN
269,2024-01-10,Coach McLoone,[],12:04,12:23,0.316667,Coach McLoone client programs,2024-01-10 12:00 https://app.asana.com/0/1195521695979971/1206304573045450/f \n—

## 1.1

In [50]:
def Invoice_Timesheet(df):
    df['Date'] = df['Name'].str.extract(r'(\d{4}-\d{2}-\d{2})', expand=False)
    invoice_columns = [
        'Date',
        'Task Project name',
        'start time',
        'end time',
        'Elapsed',
        'Task Name'
    ]
    # if include_roadmap_item:
    #     invoice_columns.insert(2, 'Roadmap Item')
    if df['Roadmap Item'].apply(lambda x: len(x)>0).sum() > 0:
        invoice_columns.insert(2, 'Roadmap Item')
    if 'Notes' in df.columns:
        invoice_columns.append('Notes')
    df = df[invoice_columns].round(2)
    df.columns = [f'| {column}' for column in df.columns]
    return df


Invoice_Timesheet(df)

,| Date,| Task Project name,| start time,| end time,| Elapsed,| Task Name,| Notes
0,2023-12-01,Solarathon,07:02,07:19,0.283333,Solarathon team communication,NaN
1,2023-12-01,Solarathon,08:10,08:30,0.333333,Solarathon meeting,NaN
2,2023-12-01,Solarathon,08:30,09:50,1.333333,Solarathon meeting,NaN
3,2023-12-01,Solarathon,09:50,09:59,0.15,Solarathon general communication,NaN
4,2023-12-01,Ginkgo meetings,11:00,11:17,0.283333,Ginkgo daily stand up meeting,NaN
...,...,...,...,...,...,...,...
265,2023-12-29,Admin,20:40,20:49,0.15,personal sprint planning,NaN
266,2023-12-29,Ginkgo app testing,20:50,21:51,1.016667,Checking Exercises Post Publishing,NaN
267,2023-12-30,Notion analytics,9:41,9:50,0.816667,learn Solara,NaN
268,2023-12-30,kinesiology continuing education,11:10,11:20,0.166667,MASS audio roundtable,NaN
269,2024-01-10,Coach McLoone,12:04,12:23,0.316667,Coach McLoone client programs,2024-01-10 12:00 https://app.asana.com/0/1195521695979971/1206304573045450/f \n—

# *End of Page*